### ISSUE TITLE
As a gamedev I want to store asset data in plaintext so asset data isn't stored in static code

### ISSUE THREAD

**Issue by AnnaSasDev** [AterraEngine/aterra_engine-cs#10]
**General**
Given AterraEngine is supposed to allow devs and end-users to easily extend the functionality of the game, having asset-data being stored in plain text could easily allow for this.
For this a clear path has to be laid out how assets are defined as "serializable", and has to easily extensible as well.

*Current idea for the structure*
```xml
<AssetData xmlns="urn:aterra-engine:asset-data">
    <requirements>
        <plugin readableName="NexitiesLib" refId="0000"/>
    </requirements>

    <assets>
        <asset assetId="0000:AE00-0000" guid="530d1c21-36eb-44ba-867e-1dc40e813b86">
            <component assetId="0000:AC00-0000">
                <value name="Translation" value="1;0"/>
                <value name="Scale" value="1;1"/>
                <value name="Rotation" value="0;0"/>
            </component>
        </asset>

        <!--    Because of the assetId we can retrieve the type needed    -->
        <asset assetId="0000:AE00-0000" guid="">
            <component assetId="0000:AC00-0000">
                <value name="Translation" value="1;0"/>
                <value name="Scale" value="1;1"/>
                <value name="Rotation" value="0;0"/>
            </component>
            <component assetId="0000:AC00-0000">
                <value name="Translation" value="1;0"/>
                <value name="Scale" value="1;1"/>
                <value name="Rotation" value="0;0"/>
            </component>

            <assetTree>
                <instance guid="530d1c21-36eb-44ba-867e-1dc40e813b86"/>
            </assetTree>
        </asset>

    </assets>
</AssetData>
```
- `Requirements` is a loose structure for which plugins are required by this asset data file, and should be parsed first as it contains the internal `PluginId` refs used within this file. These need to be mapped to the actual known `PluginId` at runtime.
- `Assets` is a collection of AssetInstance Data
   - When the `guid` is defined within the file, it usually means that this guid is required by another import.
   - 

**Notes**
- Andreas: In the future plain-text alone might not be the perfect solution. loading assets could be slowed down by opening and closing thousands of files and so on... 
- Andreas: How is the engine aware about how many assets are to be loaded, because the current loading screen depends on knowing the total count of assets?
- Andreas: An already known problem is when you need to reference from an instance in another file, it can't be known if the guid is already defined or not: Components which need outside references should have loose coupling so we can retrieve the actual instance on runtime and just store the required guid on startup.

*Keep in mind:  ASSET != Asset INSTANCE*

**Tasks**
- [x] Create a basic DTO Xml structure classes for the values
- [x] Update the auto generators for the new DTO Xml
- [x] Split up the Plugin Loading systems
    - [x] LoadedPluginDto (necessary during Engine Boot)
    - [x] PluginRecord (necessary for the PluginAtlas)
- [x] Extract engine config + plugin config into new project AterraCore.Boot 
- [x] Fix the PluginLoader & ingest LoadedPluginDto directly from PluginXml
- [ ] Allow Plugins to store `asset-data` in their `.zip`
- [ ] Define `asset-data` as a concept within the engine, meaning the data needed to create an asset instance from an asset factory
- [ ] Create an importer for the files which translates the string values into correct values the assets use

**Comment by AnnaSasDev** [comment]
Very old issue, from back when we still had HEX ids.
Will want to do something like this in the future, but with a mix of xml/json/... and code generation
