### ISSUE TITLE
As a gamedev I want to have a debug output on startupscreen of which data is being loaded

### ISSUE THREAD

**Issue by AnnaSasDev** [AterraEngine/aterra_engine-cs#12]
### General Info
A rendering specially made for debug outputs will be a required user story in the future, but for now just having th startup screen spit out some information is going to be fine.

---
#### Functional Requirements
- [ ] Debug Renderer can be enabled / disabled
- [ ] Debug Renderer is able to display special data 

#### Technical Requirements
- [ ] Debug Render System
- [ ] Debug Render Entity (how will this even work?)
- [ ] Ability to set the engine in DEBUG mode

---
### Tasks
- [ ] I have now clue for now, it will depend on the ECS after the rework at #10
