### ISSUE TITLE
As the EngineDev I want to have a "World" object which allows levels to be loaded and shown on screen

### ISSUE THREAD

**Issue by AnnaSasDev** [AterraEngine/aterra_engine-cs#15]
## General Info
Given that the "Engine" doesn't have a set "starting level", we need a system to switch between levels and coordinate their data and ECS systems.
Internally the current chosen name for this is "NexitiesWorld", but might change at a later datte.

---
### Functional Requirements
- [x] A GameDev has the ability to create their own "World" Object

### Technical Requirements
- [ ] A "World" Object controlls the loading and unloading of levels
- [ ] A "World" Object is able to be overriden as a Service

---
## Tasks
- [ ]
