### ISSUE TITLE
As a GameDev I want to store asset instance data as hardcoded

### ISSUE THREAD

**Issue by AnnaSasDev** [AterraEngine/aterra_engine-cs#16]
## General Info
Throughout the previous sprints we've been able to store the assets, aka their logic, dynamically in plugins, but now we need to focus on their instances' data.

---
### Functional Requirements
- [x] A GameDev has the ability to create instances of assets with unique contructor data
- [x] A GameDev is able to add hard coded instance data to a plugin

### Technical Requirements
- [x] Create Instances from Assets dynamically
- [ ] A Plugin has the ability to define hard coded instance data
    - [x] This hard coded data is loaded in plugin laoder sequence
    - [ ] PLuginAtlas has the ability to extract this data

---
## Tasks
- [ ] Asset Registration needs a total rework
    - [ ] InterfaceType of the asset is going to become the most important thing
- [ ] Asset Instance Atlas:
    - [x] Create
        - [ ] Add A debug check to see if `T` is creatble from `registration.Type`
    - [ ] Delete
    - [ ] Search
- [x] `IInstanceData` interface which is picked up by the `PluginRecord` to be loaded dynamically at runtime
    - [ ] Potential issue: Load order can't be define, maybe an attribute will be the best course of action for this?
- [ ] Rename Static Services into something else, maybe "NotOverridableServices"
