### ISSUE TITLE
As the EngineDev I want to create a framework for the "RootAssembly" to have easy calls for base ECS assets

### ISSUE THREAD

**Issue by AnnaSasDev** [AterraEngine/aterra_engine-cs#17]
## General Info
A root plugin always has to be defined, as this "plugin" holds the original base Nexities Assets & other overridable stuff.

---
### Technical Requirements
- [ ] From the PluginAtlas, a "RootPlugin" is able to be retrieved.
- [ ] In the load order a plugin can be defined as the root plugin, this has to be first one in the order to work correctly
    - [ ] Type 1 : Root assembly imported as a Plugin
    - [ ] Type 2 : External Plugin added as Root Plugin (aka a compiled plugin.zip)
- [ ] Library of commands to easily retrieve required root assets, types & factories for the ENGINE to work. 
    - [ ] Retrieve asset factories for base entity & component types: Level, Actor2D, etc...  

---
## Tasks
- [ ] Currently the NexitiesLib is included ONLY when using a root assembly, allow it to be assigned seperatly as well

**Comment by AnnaSasDev** [comment]
No longer necessary with the new Namespace id systems
