### ISSUE TITLE
As the EngineDev during Boot `FlowOfOperations` & `Warnings` have to bedefined, so that behaviour can be checked and validated

### ISSUE THREAD

**Issue by AnnaSasDev** [AterraEngine/aterra_engine-cs#21]
## General Info
Currently there is no flow of operations defined, or a good warning and execption system.
Some features need to be handled in different ways if they fail.

---
### Functional Requirements
- [ ] Option to break boot sequence on unstable load order
- [ ] Warnings are logged, and displayed in the console
- [ ] Dev can choose if they want to enable unstable load order
- [ ] Dev can extend the boot sequence with more features and warning handlers

### Technical Requirements
- [ ] 

---
## Tasks
- [ ]
